ERROR - 2023-08-31 16:45:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:45:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:48 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:48 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:48 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:48 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:50 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:50 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:52 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:52 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:52 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:52 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:52 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:52 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:52 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:52 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:52 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:52 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:52 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:52 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:53 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:53 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:53 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:53 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:53 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:53 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:46:53 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:46:53 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:47:15 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-31 16:47:15 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 3 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 5 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:49:11 --> mysqli_sql_exception: Unknown column 'key' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-08-31 16:49:11 --> Unknown column 'key' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `sheet1`
WHERE `key` = :key:', [...], false)
 2 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-31 16:50:34 --> mysqli_sql_exception: Unknown column 'name' in 'field list' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `name`, ...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `name`, ...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `name`, ...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `name`, ...', Array, false)
#4 C:\xampp\htdocs\ci4\app\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\app\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(915): App\Controllers\Home->index()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-08-31 16:50:34 --> Unknown column 'name' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `name`, `mobile`
FROM `sheet1`', [], false)
 2 APPPATH\Models\CommonModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Home.php(14): App\Models\CommonModel->selectQuery()
 4 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 5 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-31 17:27:05 --> Undefined variable $i
in APPPATH\Views\welcome_message.php on line 35.
 1 APPPATH\Views\welcome_message.php(35): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $i', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php', 35)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(16): view('welcome_message', [...])
 6 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-31 17:27:06 --> Undefined variable $i
in APPPATH\Views\welcome_message.php on line 35.
 1 APPPATH\Views\welcome_message.php(35): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $i', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php', 35)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(16): view('welcome_message', [...])
 6 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-31 17:28:32 --> Undefined variable $i
in APPPATH\Views\welcome_message.php on line 35.
 1 APPPATH\Views\welcome_message.php(35): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $i', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php', 35)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(16): view('welcome_message', [...])
 6 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-31 17:28:33 --> Undefined variable $i
in APPPATH\Views\welcome_message.php on line 35.
 1 APPPATH\Views\welcome_message.php(35): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $i', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php', 35)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(16): view('welcome_message', [...])
 6 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-31 17:28:33 --> Undefined variable $i
in APPPATH\Views\welcome_message.php on line 35.
 1 APPPATH\Views\welcome_message.php(35): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $i', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php', 35)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(16): view('welcome_message', [...])
 6 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-31 17:28:33 --> Undefined variable $i
in APPPATH\Views\welcome_message.php on line 35.
 1 APPPATH\Views\welcome_message.php(35): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $i', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php', 35)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(16): view('welcome_message', [...])
 6 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-31 17:28:56 --> Undefined variable $i
in APPPATH\Views\welcome_message.php on line 43.
 1 APPPATH\Views\welcome_message.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $i', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php', 43)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(16): view('welcome_message', [...])
 6 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-31 17:28:56 --> Undefined variable $i
in APPPATH\Views\welcome_message.php on line 43.
 1 APPPATH\Views\welcome_message.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $i', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php', 43)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(16): view('welcome_message', [...])
 6 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-31 17:28:56 --> Undefined variable $i
in APPPATH\Views\welcome_message.php on line 43.
 1 APPPATH\Views\welcome_message.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $i', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php', 43)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(16): view('welcome_message', [...])
 6 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-31 17:28:56 --> Undefined variable $i
in APPPATH\Views\welcome_message.php on line 43.
 1 APPPATH\Views\welcome_message.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $i', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php', 43)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(16): view('welcome_message', [...])
 6 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-31 17:28:56 --> Undefined variable $i
in APPPATH\Views\welcome_message.php on line 43.
 1 APPPATH\Views\welcome_message.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $i', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php', 43)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(16): view('welcome_message', [...])
 6 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-31 17:28:57 --> Undefined variable $i
in APPPATH\Views\welcome_message.php on line 43.
 1 APPPATH\Views\welcome_message.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $i', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php', 43)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\welcome_message.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('welcome_message', [], true)
 5 APPPATH\Controllers\Home.php(16): view('welcome_message', [...])
 6 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
